services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - msvc_network

  msvc-autorizacion:
    build:
      context: .
      dockerfile: msvc-autorizacion/Dockerfile
    container_name: msvc-autorizacion
    restart: always
    ports:
      - "8001:8010"
    environment:
      - SERVER_PORT=8010
      - DB_HOST=db
      - DB_NAME=db_autorizacion
      - DB_USER=root
      - DB_PASS=1234
    depends_on:
      - db
    networks:
      - msvc_network

volumes:
  db_data:

networks:
  msvc_network: