server:
  port: 8080
jwt:
    secret-key: ${JWT_SECRET_KEY}
    token-prefix: Bearer
    header-string: Authorization
    expiration: 3600 #En segundos

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters: # Filtro por defecto para todas las rutas
        - name: AuthenticationFilter
      routes:
        - id: msvc-autorizacion
          uri: http://msvc-autorizacion:8010
          predicates:
            - Path=/auth/**
        - id: msvc-monopatines
          uri: http://msvc-monopatines:8001
          predicates:
            - Path=/api/monopatin/**
        - id: msvc-admin
          uri: http://msvc-admin:8005
          predicates:
            - Path=/api/admin/**
        - id: msvc-paradas
          uri: http://msvc-paradas:8003
          predicates:
            - Path=/api/parada/**
        - id: msvc-usuarios
          uri: http://msvc-usuarios:8002
          predicates:
            - Path=/api/usuario/**
        - id: msvc-viajes
          uri: http://msvc-viajes:8007
          predicates:
            - Path=/api/viaje/**