openapi: 3.0.3
info:
  title: API Chatbot Monopatines Eléctricos
  version: 1.0.0
  description: API para gestionar mensajes y respuestas del chatbot de asistencia técnica para un sistema de gestión de monopatines eléctricos.
servers:
  - url: http://localhost:3010/api/chat
paths:
  /chatbot:
    post:
      summary: Obtener respuesta del chatbot
      description: Envía un mensaje al chatbot y recibe una respuesta generada, guardando ambos mensajes en la base de datos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - message
              properties:
                userId:
                  type: string
                  description: ID del usuario que envía el mensaje.
                message:
                  type: string
                  description: Mensaje enviado por el usuario.
      responses:
        '200':
          description: Respuesta generada por el chatbot.
          content:
            application/json:
              schema:
                type: string
                example: "¡Hola! ¿En qué puedo ayudarte con tu monopatín eléctrico?"
        '400':
          description: Faltan parámetros requeridos.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "userId y message son requeridos"
        '404':
          description: No se pudo obtener la respuesta del chat.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "No se pudo obtener la respuesta del chat"
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "No se pudo obtener la respuesta del chat"
  /historial/{id}:
    get:
      summary: Obtener historial de chat por usuario
      description: Devuelve el historial de mensajes de chat asociados a un usuario.
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: ID del usuario.
      responses:
        '200':
          description: Historial de chat del usuario.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: string
                    message:
                      type: string
                    role:
                      type: string
                      enum: [user, assistant]
                    createdAt:
                      type: string
                      format: date-time
        '404':
          description: No se encontraron chats para este usuario.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "No se encontraron chats para este usuario"
        '500':
          description: Error interno al obtener el historial.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "No se pudo obtener el historial"
components:
  schemas: {}