# version: '3.8'

services:
  node-app-chat:
    container_name: node-app-chat
    build:
      context: . # Ruta del Dockerfile
      dockerfile: nodeDocker/Dockerfile
    ports:
      - "3010:3010" # Host:Contenedor
    environment:
      NODE_ENV: production
      PORT: 3010
    volumes:
      - .:/app # Monta el código (modo desarrollo)
      - /app/node_modules # Evita sobrescribir dependencias
    restart: unless-stopped
    networks:
      - msvc_network
    depends_on:
      - mongo

  mongo:
    container_name: mongo-db-chat
    build:
      context: ./mongoDocker # Ruta del Dockerfile
      dockerfile: Dockerfile
    logging:
      driver: "none" # ni consola ni docker logs
    restart: unless-stopped
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27018:27018"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - msvc_network

volumes:
  mongo-data:

networks:
  msvc_network:
    external: true
